

--  SINH VIEN
ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_MACHUYENNGANH
FOREIGN KEY (MACHUYENNGANH) REFERENCES CHUYENNGANH(MACHUYENNGANH)
 

 ALTER TABLE GIANGVIEN
ADD CONSTRAINT FK_GIANGVIEN_MAKHOA
FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE  KHOA
ADD CONSTRAINT FK_KHOA_MATRUONGKHOA
FOREIGN KEY (MATRUONGKHOA)  REFERENCES GIANGVIEN(MSGV)

ALTER TABLE CHUYENNGANH
ADD CONSTRAINT FK_CHUYENNGANH_MAKHOA
FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_MACHUYENNGANH
FOREIGN KEY (MACHUYENNGANH) REFERENCES CHUYENNGANH(MACHUYENNGANH)

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_MAKHOA
FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE LOPSINHHOAT
ADD CONSTRAINT FK_LOPSINHHOAT_MACHUYENNGANH
FOREIGN KEY (MACHUYENNGANH) REFERENCES CHUYENNGANH(MACHUYENNGANH)

ALTER TABLE  LOPSINHHOAT
ADD CONSTRAINT FK_LOPSINHHOAT_MACOVAN
FOREIGN KEY (MACOVAN)  REFERENCES GIANGVIEN(MSGV)


ALTER TABLE  LOPMONHOC
ADD CONSTRAINT FK_LOPMONHOC_MAMON
FOREIGN KEY (MAMON)  REFERENCES MONHOC(MAMH)

ALTER TABLE  LOPMONHOC
ADD CONSTRAINT FK_LOPMONHOC_MSGV
FOREIGN KEY (MSGV)  REFERENCES GIANGVIEN(MSGV)


ALTER TABLE  DETHI
ADD CONSTRAINT FK_DETHI_MAMON
FOREIGN KEY (MAMH)  REFERENCES MONHOC(MAMH)


ALTER TABLE  SINHVIEN_MONHOC
ADD CONSTRAINT FK_SINHVIEN_MONHOC_MSSV
FOREIGN KEY (MSSV)  REFERENCES SINHVIEN(MSSV)

ALTER TABLE  SINHVIEN_MONHOC
ADD CONSTRAINT FK_SINHVIEN_MONHOC_MALOPMH
FOREIGN KEY (MALOPMH)  REFERENCES LOPMONHOC(MALOPMH)

ALTER TABLE  SINHVIEN_MONHOC
ADD PRIMARY KEY (MSSV,MALOPMH)


ALTER TABLE CDR_MH
ADD CONSTRAINT FK_CDR_MH_MAMH
FOREIGN KEY (MAMH)  REFERENCES MONHOC(MAMH)

ALTER TABLE  CDR_MH
ADD PRIMARY KEY (MAMH,CDRMH,CDRKH)


ALTER TABLE CDR_CN
ADD CONSTRAINT FK_CDR_CN_MACHUYENNGANH
FOREIGN KEY (MACHUYENNGANH)  REFERENCES CHUYENNGANH(MACHUYENNGANH)

ALTER TABLE  CDR_CN
ADD PRIMARY KEY (MACHUYENNGANH,CDRKH)


ALTER TABLE CAUTRUCDT
ADD CONSTRAINT FK_CAUTRUCDT_MADT
FOREIGN KEY (MADT)  REFERENCES DETHI(MADT)

ALTER TABLE  CAUTRUCDT
ADD PRIMARY KEY (MADT,CAU,CDR)


ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MASV
FOREIGN KEY (MSSV)  REFERENCES SINHVIEN(MSSV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MAMH
FOREIGN KEY (MAMH)  REFERENCES MONHOC(MAMH)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MADT
FOREIGN KEY (MADT)  REFERENCES DETHI(MADT)

ALTER TABLE KETQUATHI
ADD PRIMARY KEY (MSSV,MAMH,MADT,CAU)
