USE MASTER 

CREATE DATABASE DATABASENAME
--DROP DATABASE DATABASENAME
USE DATABASENAME

CREATE TABLE SINHVIEN
(
	MSSV CHAR(8) PRIMARY KEY,
	TENSV NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(30),
	SODT NVARCHAR(10),
	NIENKHOA NVARCHAR(10),
	MACHUYENNGANH NVARCHAR(10), 
	PASSW NVARCHAR(30),
)

--DROP TABLE SINHVIEN

CREATE TABLE GIANGVIEN
(
	MSGV NVARCHAR(10) PRIMARY KEY,
	TENGV NVARCHAR(30),
	PASSW NVARCHAR(30),
	SODT NVARCHAR(10),
	DIACHI NVARCHAR(30),
	HOCVI NVARCHAR(30),
	MAKHOA NVARCHAR(10),
)


--DROP TABLE GIANIEN

CREATE TABLE KHOA
(
	MAKHOA NVARCHAR(10) PRIMARY KEY,
	TENKHOA NVARCHAR(30),
	MATRUONGKHOA NVARCHAR(10),
)

--DROP TABLE KHOA

CREATE TABLE CHUYENNGANH
(
	MACHUYENNGANH NVARCHAR(10) PRIMARY KEY, 
	TENCN NVARCHAR(30),
	MAKHOA NVARCHAR(10),
	SOLUONGCDR NVARCHAR(10)
)

--DROP TABLE CHUYENNGANH

CREATE TABLE MONHOC
(
	MAMH NVARCHAR(10) PRIMARY KEY, 
	TENMH NVARCHAR(30),  
	MAKHOA NVARCHAR(10),
	MACHUYENNGANH NVARCHAR(10),
	TINCHI INT
) 


--DROP TABLE MONHOC

CREATE TABLE LOPSINHHOAT
(
	MALOPSH NVARCHAR(10) PRIMARY KEY, 
	TENLOP NVARCHAR(30), 
	MAKHOA NVARCHAR(10), 
	MACHUYENNGANH NVARCHAR(10), 
	MACOVAN NVARCHAR(10)
)

--DROP TABLE LOPSINHHOAT
CREATE TABLE LOPMONHOC
(
	MALOPMH NVARCHAR(10) PRIMARY KEY, 
	TENLOPMH NVARCHAR(30), 
	HOCKI NVARCHAR(30), 
	NAM NVARCHAR(30),  
	MAMON NVARCHAR(10), 
	MSGV NVARCHAR(10),
)

--DROP TABLE LOPMONHOC
CREATE TABLE DETHI
(
	MADT NVARCHAR(10) PRIMARY KEY, 
	MAMH NVARCHAR(10),
	HK NVARCHAR(10), 
	NAMHOC NVARCHAR(10),
	LOAI NVARCHAR(10),
	SOCAU INT
)


--DROP TABLE DETHI
CREATE TABLE SINHVIEN_MONHOC
(
	MSSV CHAR(8) NOT NULL, 
	MALOPMH NVARCHAR(10) NOT NULL,
	DIEMQT FLOAT, 
	DIEMGK FLOAT, 
	DIEMTH FLOAT,
	DIEMCK FLOAT
)	


--DROP TABLE SINHVIEN_MONHOC
CREATE TABLE CDR_MH
(
	MAMH NVARCHAR(10) NOT NULL, 
	CDRMH NVARCHAR(10) NOT NULL, 
	CDRKH NVARCHAR(10) NOT NULL
)

--DROP TABLE SINHVIEN_MONHOC

CREATE TABLE CDR_CN
(
	MACHUYENNGANH NVARCHAR(10) NOT NULL,
	CDRKH NVARCHAR(10) NOT NULL
)


--DROP TABLE CDR_CN
CREATE TABLE CAUTRUCDT
(
	MADT NVARCHAR(10) NOT NULL,
	CAU INT NOT NULL,
	CDR NVARCHAR(10) NOT NULL,
	DIEMTOIDA INT NOT NULL,
) 


--DROP TABLE CAUTRUCDT

CREATE TABLE KETQUATHI
(
	MSSV CHAR(8) NOT NULL, 
	MAMH  NVARCHAR(10) NOT NULL,
	MADT NVARCHAR(10) NOT NULL,
	CAU INT NOT NULL,
	DIEM FLOAT,	
)
