Create PROC PROC_IN_MSSV_MAMH_KQ
	@mssv char(8),
	@malopmh nvarchar(10)
AS
BEGIN
	DECLARE @mamh nvarchar(10)
	SELECT @mamh = MAMON  
	FROM LOPMONHOC
	WHERE MALOPMH = @malopmh

	SELECT KQT.MSSV, KQT.MAMH, 
	KQT.MADT,DETHI.LOAI, DETHI.HK, DETHI.NAMHOC, KQT.CAU, KQT.DIEM,CTDT.DIEMTOIDA,CTDT.CDR 
	FROM KETQUATHI KQT, CAUTRUCDT CTDT, DETHI
	WHERE  KQT.MADT = CTDT.MADT AND KQT.CAU = CTDT.CAU  AND DETHI.MADT = CTDT.MADT AND 
	MSSV = @mssv AND KQT.MAMH = @mamh 
END
GO
 DROP PROC PROC_IN_MSSV_MAMH

EXEC PROC_IN_MSSV_MAMH '12340001', 'IE204.I32' 

SELECT SVMH.MSSV,SVMH.MALOPMH,SVMH.DIEMQT,SVMH.DIEMGK,SVMH.DIEMTH,SVMH.DIEMGK,MONHOC.TINCHI
FROM SINHVIEN_MONHOC SVMH, MONHOC,LOPMONHOC 
WHERE MSSV = '12340001' AND SVMH.MALOPMH= LOPMONHOC.MALOPMH AND LOPMONHOC.MAMON = MONHOC.MAMH

ALTER PROC PROC_IN_MSSV_MAMH 
	@mssv char(8),
	@malopmh nvarchar(10)
AS
BEGIN
	DECLARE @mamh nvarchar(10)
	SELECT @mamh = MAMON  
	FROM LOPMONHOC
	WHERE MALOPMH = @malopmh

	SELECT KQT.MSSV, KQT.MAMH, 
	KQT.MADT,DETHI.LOAI, DETHI.HK, DETHI.NAMHOC, KQT.CAU, KQT.DIEM,CTDT.DIEMTOIDA,CTDT.CDR ,CDR_MH.CDRKH
	FROM KETQUATHI KQT, CAUTRUCDT CTDT, DETHI, CDR_MH
	WHERE  KQT.MADT = CTDT.MADT AND KQT.CAU = CTDT.CAU  AND DETHI.MADT = CTDT.MADT AND 
	MSSV = @mssv AND KQT.MAMH = @mamh AND CDR_MH.MAMH = KQT.MAMH AND CDR_MH.CDRMH= CTDT.CDR
END
GO
-- DROP PROC PROC_IN_MSSV_MAMH


EXEC PROC_IN_MSSV_MAMH '12340001', 'IE204.I32' 





